# Generated by Django 4.2.4 on 2023-08-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='img',
            new_name='imgd',
        ),
    ]
